### ISSUE TITLE
Time Fast-forward issue?

### ISSUE THREAD

**Issue by mpql** [alexb5dh/TimeSpeed#1]
I'm not sure what caused it, but I was using the v2.0.1 version of this mod from the releases section on Stardew Valley 1.1 (File version 1.0.6124.25603) and I entered my barn as it was turning just about 5pm or so, and it  fast-forwarded to 2am and made me pass out. Then it saved and whatnot, and I woke in my bed at 2am, about to pass out again while still in bed. I alt+F4'd to avoid losing a day, and upon relaunch the issue was gone, but I figured it was worth reporting.

Config file is attached here: [config.zip](https://github.com/alexb5dh/TimeSpeed/files/558378/config.zip). My brain's auto-pilot saved it as I went to look at it, so its modified timestamp might be a couple of minutes before this writing, but it wasn't actually modified.

Either way, thanks for updating this mod! I prefer playing Stardew Valley with time settings closer to Harvest Moon 64. :)

**Comment by alexb5dh** [comment]
Should be fixed in version 2.0.2
See fa021894e8108287b296e494bc0cb5cc2ec8653e

Apologies for such delayed response
